export const Codes = {
    STX0001: "Too many requests from this IP, please try again after 15 minutes",
    STX0002: "User already registered in the system!",
    STX0003: "User registered successfully!",
    STX0004: "User logged in successfully!",
    STX0005: "Password is incorrect!",
    STX0006: "Please provide token",
    STX0007: "User logged out successfully!",
    STX0008: "User login failed!",
    STX0009: "User logout failed!",
    STX0010: "User registeration failed!",
    STX0011: "User not found!",
    STX0012: "Token is blacklisted",
    STX0013: "Password changed successfully!",
    STX0014: "Error generating token!",
    STX0015: "Old password is incorrect!",
    STX0016: "Old password and new password are same",
    STX0017: "You are not authorized to perform this action",
}