export const Codes = {
    STX0001: "Too many requests from this IP, please try again after 15 minutes",
    STX0002: "User already registered in the system!",
    STX0003: "User registered successfully!",
    STX0004: "User logged in successfully!",
    STX0005: "Password is incorrect!",
    STX0006: "Please provide token",
    STX0007: "User logged out successfully!",
    STX0008: "User login failed!",
    STX0009: "User logout failed!",
    STX0010: "User registeration failed!",
    STX0011: "User not found!",
    STX0012: "Token is blacklisted",
    STX0013: "Password changed successfully!",
    STX0014: "Error generating token!",
    STX0015: "Old password is incorrect!",
    STX0016: "Old password and new password are same",
    STX0017: "You are not authorized to perform this action",
    STX0018: "User details fetched successfully",   
    STX0019: "Users fetched successfully",   
    STX0020: "No users present",   
    STX0021: "Schema is required",   
    STX0022: "User details updated successfully",   
    STX0023: "User is deactivated",   
    STX0024: "Username is required",   
    STX0025: "User deleted successfully",   
    STX0026: "Cannot delete the last admin user",   
    STX0027: "Brand created successfully",   
    STX0028: "Brand(s) fetched successfully", 
    STX0029: "No brands present",   
    STX0030: "Brand not found",   
    STX0031: "Brand updated successfully",   
    STX0032: "Brand deleted successfully",   
    STX0033: "Product created successfully",   
    STX0034: "Products created successfully",   
    STX0035: "Product(s) fetched successfully",   
    STX0036: "Product not found",   
    STX0037: "No products present",   
    STX0038: "Product deleted successfully",   
    STX0039: "Product updated successfully",   
    STX0040: "Color created successfully",   
    STX0041: "Color updated successfully",
    STX0042: "Color deleted successfully",
    STX0043: "Color(s) fetched successfully",
    STX0044: "Color not found",
    STX0045: "No colors present",
    STX0046: "Size Range created successfully",
    STX0047: "Size Range updated successfully",
    STX0048: "All Size Ranges fetched successfully",   
    STX0049: "No Size Ranges present",   
    STX0050: "No Size Ranges present with the given ids,please check the ids",   
    STX0051: "Size Range deleted successfully",  
    STX0052: "Size Range not found", 
}